/****************************************************************************************************

	SQLHACK DB ENVIORNMENT RESET SCRIPT - LEGACY SQL2008 INSTANCE
	=================================================

RUN AGAINST: [LEGACYSQL2008]

PURPOSE: 
1. checks it's being run against the legacy SQL Server instance	
2. Makes sure CLR is enabled on the legacy environment
3. Lowers the trust settings for the CLR SPs so they don't throw warnings/errors in DMA

****************************************************************************************************/
IF @@SERVERNAME <> 'LEGACYSQL2008' 
   RAISERROR('*** NOT CONNECTED TO [LEGACYSQL2008] INSTANCE ***', 20, 1) WITH LOG;

USE master;
GO
EXEC sp_configure 'clr enabled', 1;
GO
RECONFIGURE;
GO

USE TEAM01_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team01_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM02_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team02_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM03_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team03_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO


USE TEAM04_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team04_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM05_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team05_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM06_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team06_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM07_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team07_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM08_TenantDataDb;
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team08_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM09_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team09_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM10_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team10_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM11_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team11_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM12_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team12_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM13_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team13_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM14_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team14_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM15_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team15_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM16_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team16_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM17_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team17_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM18_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team18_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM19_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team19_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM20_TenantDataDb
GO
EXEC sp_changedbowner 'sa'
GO
ALTER DATABASE Team20_TenantDataDb SET TRUSTWORTHY ON
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO


/****************************************************************************************************

					END SCRIPT

****************************************************************************************************/
