/****************************************************************************************************

	SQLHACK DB ENVIORNMENT RESET SCRIPT - LEGACY SQL2008 INSTANCE
	=================================================

RUN AGAINST: [LEGACYSQL2008]

PURPOSE: 
1. checks it's being run against the legacy SQL Server instance	
2. Makes sure CLR is enabled on the legacy environment
3. Lowers the trust settings for the CLR SPs so they don't throw warnings/errors in DMA

****************************************************************************************************/
IF @@SERVERNAME <> 'LEGACYSQL2008' 
   RAISERROR('*** NOT CONNECTED TO [LEGACYSQL2008] INSTANCE ***', 20, 1) WITH LOG;

USE master;
GO
EXEC sp_configure 'clr enabled', 1;
GO
RECONFIGURE;
GO

USE TEAM01_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM02_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM03_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO


USE TEAM04_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM05_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM06_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM07_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM08_TenantDataDb;
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM09_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM10_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM11_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM12_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM13_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM14_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM15_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM16_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM17_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM18_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM19_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO

USE TEAM20_TenantDataDb
GO
ALTER ASSEMBLY CLRUFDS WITH PERMISSION_SET = UNSAFE;
ALTER ASSEMBLY Database1 WITH PERMISSION_SET = UNSAFE;
GO


/****************************************************************************************************

					END SCRIPT

****************************************************************************************************/

